# Making reusable composite actions documented at
# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action#creating-a-composite-action-within-the-same-repository
name: 'Download the artifact or build from source if failed'
description: 'Fetch or, if failed, build the binaries'
defaults:
  shell: bash --noprofile --norc -eo pipefail -x {0}
inputs:
  artifact-name:
    description: 'The name of the artifact to fetch and unpack (it must contain the target.tar file)'
    required: true
  build-profile:
    description: 'Choose the build profile for cascade (release/debug)'
    required: false
    default: debug
runs:
  using: "composite"
  steps:
  - name: Verify inputs
    run: |
      [[ "${{ inputs.build-profile }}" =~ ^debug|release$ ]]
  - uses: actions/download-artifact@v5
    id: download_binaries
    # Don't mark this run as failed if downloading the cached version fails,
    # we are building from source below if that happens. Inspired by:
    # https://github.com/actions/runner/issues/2679#issuecomment-1645222952
    continue-on-error: true
    with:
      name: ${{ inputs.artifact-name }}
  - name: Extract downloaded binaries
    # due to 'continue-on-error: true' above the conclusion/status will
    # always be success, but we can check for success using the outcome key
    if: ${{ steps.download_binaries.outcome == 'success' }}
    run: tar -xf target.tar
  - name: Build from source if downloading artifacts failed
    # due to 'continue-on-error: true' above the conclusion/status will
    # always be success, but we can check for failure using the outcome key
    if: ${{ steps.download_binaries.outcome == 'failure' }}
    run: |
      case "${{ inputs.build-profile }}" in
        debug)
          cargo build
          ;;
        release)
          cargo build --release
          ;;
        *) exit 1
      esac
  - name: Build dnst from keyset branch
    if: ${{ steps.download_binaries.outcome == 'failure' }}
    run: |
      case "${{ inputs.build-profile }}" in
        debug)
          cargo install --debug --git https://github.com/nlnetlabs/dnst --branch keyset --root "$GITHUB_WORKSPACE/target/dnst" --locked --bin=dnst
          ;;
        release)
          cargo install --git https://github.com/nlnetlabs/dnst --branch keyset --root "$GITHUB_WORKSPACE/target/dnst" --locked --bin=dnst
          ;;
        *) exit 1
      esac
  - name: Add dnst to PATH
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#example-of-adding-a-system-path
    run: echo "$GITHUB_WORKSPACE/target/dnst/bin" >> "$GITHUB_PATH"
