# Making reusable composite actions documented at
# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action#creating-a-composite-action-within-the-same-repository
name: 'Download the artifact or build from source if failed'
description: 'Fetch or, if failed, build the binaries'
defaults:
  shell: bash --noprofile --norc -eo pipefail -x {0}
inputs:
  artifact-name:
    description: 'The name of the artifact to fetch and unpack (it must contain the target.tar file)'
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/download-artifact@v5
    id: download_binaries
    # Don't mark this run as failed if downloading the cached version fails,
    # we are building from source below if that happens. Inspired by:
    # https://github.com/actions/runner/issues/2679#issuecomment-1645222952
    continue-on-error: true
    with:
      name: ${{ inputs.artifact-name }}
  - name: Extract downloaded binaries
    # due to 'continue-on-error: true' above the conclusion/status will
    # always be success, but we can check for success using the outcome key
    if: ${{ steps.download_binaries.outcome == 'success' }}
    run: tar -xf target.tar
  - name: Build from source if downloading artifacts failed
    # due to 'continue-on-error: true' above the conclusion/status will
    # always be success, but we can check for failure using the outcome key
    if: ${{ steps.download_binaries.outcome == 'failure' }}
    run: |
      case "${{ env.build-profile }}" in
        debug)
          cargo build
          ;;
        release)
          cargo build --release
          ;;
        *) exit 1
      esac
  - name: Build dnst from keyset branch
    if: ${{ steps.download_binaries.outcome == 'failure' }}
    run: |
      case "${{ env.build-profile }}" in
        debug)
          cargo install --debug --git https://github.com/nlnetlabs/dnst --branch keyset --root "$GITHUB_WORKSPACE/target/dnst" --locked --bin=dnst
          ;;
        release)
          cargo install --git https://github.com/nlnetlabs/dnst --branch keyset --root "$GITHUB_WORKSPACE/target/dnst" --locked --bin=dnst
          ;;
        *) exit 1
      esac
  - name: Add cascade to PATH
    run: |
      case "${{ env.build-profile }}" in
        debug)
          [[ -x "$GITHUB_WORKSPACE/target/debug/cascaded" ]] # Sanity check
          echo "$GITHUB_WORKSPACE/target/debug" >> "$GITHUB_PATH"
          ;;
        release)
          [[ -x "$GITHUB_WORKSPACE/target/release/cascaded" ]] # Sanity check
          echo "$GITHUB_WORKSPACE/target/release" >> "$GITHUB_PATH"
          ;;
        *) exit 1
      esac
  - name: Add dnst to PATH
    # https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-commands#example-of-adding-a-system-path
    run: |
      case "${{ env.build-profile }}" in
        debug)
          # Sanity check
          if ! [[ -x "$GITHUB_WORKSPACE/target/dnst/debug/bin/dnst" ]]; then
            echo "::error:: dnst binary ($GITHUB_WORKSPACE/target/dnst/debug/bin/dnst) is not executable"
          fi
          echo "$GITHUB_WORKSPACE/target/dnst/debug/bin" >> "$GITHUB_PATH"
          ;;
        release)
          if ! [[ -x "$GITHUB_WORKSPACE/target/dnst/release/bin/dnst" ]]; then
            echo "::error:: dnst binary ($GITHUB_WORKSPACE/target/dnst/release/bin/dnst) is not executable"
          fi
          echo "$GITHUB_WORKSPACE/target/dnst/release/bin" >> "$GITHUB_PATH"
          ;;
        *) exit 1
      esac
