#!/usr/bin/env bash
set -e

#exec >/dev/tty
exec >/tmp/hook.out 2>&1
echo "Signed review hook"

TEST_DIR="<INTEGRATION_TEST_DIR>"

export LC_ALL=C

# Set the port for the unsigned review server manually until it gets passed
# by Cascade.
CASCADE_SERVER_PORT=4541

case X"$CASCADE_SERIAL" in
X11111)
	ref="$TEST_DIR/reference-output/test1.sorted"
;;
X22222)
	ref="$TEST_DIR/reference-output/test2.sorted"
;;
*)
	exit 1
;;
esac
#dig -p "$CASCADE_SERVER_PORT" @"$CASCADE_SERVER_IP" "$CASCADE_ZONE" axfr >/tmp/dig.out 
diff -iwu <(dig -p "$CASCADE_SERVER_PORT" @"$CASCADE_SERVER_IP" "$CASCADE_ZONE" axfr |
	sed '0,/SOA/d;s/[ \t]*;.*//' |
	egrep -v '^$' | sort) \
	<(cat "$ref")
exit 0
