# Setup incremental signing to produce predictable outputs so that we can
# easily compare the generated zone against expected output.
#
# Enable sending of NOTIFY messages to the NSD secondary.
version = "v1"

[signer.denial]
type = "nsec"

[signer]
serial-policy = "counter"
signature-inception-offset = 0
signature-lifetime = 100
signature-remain-time = 90
signature-refresh-interval = 1

[key-manager.records]
dnskey.signature-inception-offset = 0
cds.signature-inception-offset = 0
dnskey.signature-lifetime = 10
cds.signature-lifetime = 10

[server.outbound]
# NSD secondary listens on port 1054.
send-notify-to = ["127.0.0.1:1054"]
