# Making reusable composite actions documented at
# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action#creating-a-composite-action-within-the-same-repository
name: 'Setup and start cascade'
description: 'Setup and start the cascade daemon'
defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail -x {0}
inputs:
  cascade-dir:
    description: 'The name of the artifact to fetch and unpack (it must contain the target.tar file)'
    required: false
    default: ${{ github.workspace }}/cascade-dir
runs:
  using: "composite"
  steps:
  - name: Start cascade with a working-directory-local config
    run: |
      CASCADE_DIR="${{ inputs.cascade-dir }}"

      mkdir -p "${CASCADE_DIR}/policies"
      # We need to create a custom config for cascade because the default paths are not available/permitted in this environment
      cascade template config | \
        "${GITHUB_WORKSPACE}/integration-tests/scripts/sed-config-dirs.sh" "${CASCADE_DIR}" | tee "${CASCADE_DIR}/config.toml" >/dev/null
      cascade template policy > "${CASCADE_DIR}/policies/default.toml"
      cascaded --config "${CASCADE_DIR}/config.toml" --state "${CASCADE_DIR}/state.db" --daemonize &>"${CASCADE_DIR}/cascade-startup.log"
