# Making reusable composite actions documented at
# https://docs.github.com/en/actions/tutorials/create-actions/create-a-composite-action#creating-a-composite-action-within-the-same-repository
name: 'Setup and start cascade'
description: 'Setup and start the cascade daemon'
defaults:
  shell: bash --noprofile --norc -eo pipefail -x {0}
inputs:
  cascade-dir:
    description: 'The name of the artifact to fetch and unpack (it must contain the target.tar file)'
    required: false
    default: ${{ github.workspace }}/cascade-dir
  build-profile:
    description: 'Choose the build profile for cascade (release/debug)'
    required: false
    default: debug
runs:
  using: "composite"
  steps:
  - name: Start cascade with a working-directory-local config
    run: |
      # Adding an underscore before CARGO to prevent accidental conflicts with actual CARGO env variables
      _CARGO_PROFILE=${{ inputs.build-profile }}
      case "$_GARGO_PROFILE" in
        debug) CASCADE_BIN=${GITHUB_WORKSPACE}/target/debug/cascade ;;
        release) CASCADE_BIN=${GITHUB_WORKSPACE}/target/release/cascade ;;
        *) exit 1
      esac
      CASCADE_DIR=${{ inputs.cascade-dir }}

      mkdir -p "${CASCADE_DIR}/policies"
      # We need to create a custom config for cascade because the default paths are not available/permitted in this environment
      "$CASCADE_BIN" template config | \
        "${GITHUB_WORKSPACE}/scripts/sed-config-dirs.sh" "${CASCADE_DIR}" | tee "${CASCADE_DIR}/config.toml" >&2
      "$CASCADE_BIN" template policy > "${CASCADE_DIR}/policies/default.toml"
      "$CASCADE_BIN" --config "${CASCADE_DIR}/config.toml" --state "${CASCADE_DIR}/state.db" --daemonize &>"${CASCADE_DIR}/cascade-startup.log"
