//! Instances of zones.
//!
//! An _instance_ is a snapshot of the contents of a zone (the specific records
//! within it). Cascade maintains information about various instances, e.g. how
//! they were generated and information needed to re-sign them.
//!
//! Instances can be classified by their origin and purpose: _loaded_ instances
//! are generated by Cascade's zone loader (by loading from a configured zone
//! source) and _signed_ instances are generated by the zone signer (by signing
//! a loaded instance or re-signing a prior signed instance). An "instance" in
//! general refers to a pair of loaded and signed instances (where the signed
//! instance was generated from the loaded instance).
//!
//! Instances (whether loaded or signed) can be in one of four states:
//!
//! - _Upcoming_ (i.e. _Next_): The instance is being generated and reviewed. If
//!   all goes well, it will become _Current_.
//!
//! - _Current_ (i.e. _Published_): The instance has been accepted and is now
//!   being published by Cascade as the latest authoritative version.
//!
//! - _Obsolete_: The instance was previously _Current_, but has since been
//!   replaced by a new _Current_ instance.
//!
//! - _Abandoned_: The instance failed to be accepted (e.g. due to an error in
//!   generation or being rejected at review).
//!
//! Instances are tracked by [`Instances`]. At any time, there are (at most)
//! one loaded+signed pair of upcoming instances, and one loaded+signed pair
//! of current instances. There may be any number of obsolete and abandoned
//! instances.

use std::num::NonZeroU64;

use cascade_zonedata::SoaRecord;
use domain::new::base::Serial;

//----------- Instances --------------------------------------------------------

/// State regarding instances of the zone.
///
/// See the module-level documentation for more information.
#[derive(Debug, Default)]
pub struct Instances {
    /// The upcoming instance, if any.
    ///
    /// This is [`Some`] when a new instance is being built (a new instance of
    /// the zone is being loaded, or the zone is being re-signed).
    pub upcoming: Option<UpcomingInstance>,

    /// The current/published instance.
    ///
    /// In general, this will be [`Some`]; most zones have a current instance.
    /// It is [`None`] if an instance of the zone has never been accepted, or
    /// the instance could not be restored from disk on startup.
    pub current: Option<CurrentInstance>,

    /// The instance persisted to disk.
    ///
    /// This is set when Cascade restarts after persisting the zone to disk.
    /// This field stores the zone that _was_ the current/published instance;
    /// it will be moved to [`Self::current`] if/when restoration succeeds. If
    /// restoration fails, it remains untouched here; thus this field is never
    /// modified.
    pub persisted: Option<PersistedInstance>,
    //
    // TODO:
    // - The next usable loaded/signed instance IDs.
    //   These increase monotonically, even if instances are abandoned.
    // - Obsolete instances.
    // - Abandoned instances.
}

/// # Initiating operations
impl Instances {
    /// Initiate a new operation.
    ///
    /// An upcoming instance will be prepared.
    ///
    /// ## Panics
    ///
    /// Panics if an upcoming instance already exists.
    pub fn start_load(&mut self) {
        assert!(
            self.upcoming.is_none(),
            "Cannot start a load while an upcoming instance exists",
        );

        self.upcoming = Some(UpcomingInstance {
            loaded: None,
            signed: None,
        });
    }

    /// Initiate a re-sign operation.
    ///
    /// ## Panics
    ///
    /// Panics if:
    /// - An upcoming instance already exists.
    /// - There is no current loaded instance of the zone.
    pub fn start_resign(&mut self) {
        assert!(
            self.upcoming.is_none(),
            "Cannot start a re-sign while an upcoming instance exists",
        );

        assert!(
            self.current.is_some(),
            "Cannot start a re-sign without a current loaded instance",
        );

        self.upcoming = Some(UpcomingInstance {
            loaded: None,
            signed: None,
        });
    }

    /// Clear the current instance.
    ///
    /// This method should be called if the data for the zone is being cleared.
    /// The current instance (if any) will be abandoned.
    ///
    /// ## Panics
    ///
    /// Panics if there is an upcoming instance of the zone. This method must be
    /// called after the upcoming instance is resolved (applied or abandoned).
    pub fn clear(&mut self) {
        // TODO: Save the current instance to a list of obsolete ones.

        assert!(
            self.upcoming.is_none(),
            "Cannot modify the current instance while an upcoming one exists"
        );

        self.current = None;
    }
}

/// # Loading operations
impl Instances {
    /// Finish an ongoing load.
    ///
    /// ## Panics
    ///
    /// Panics if:
    /// - There is no upcoming instance of the zone.
    /// - The upcoming instance is not empty.
    /// - `built` contains an empty instance.
    pub fn finish_load(&mut self, built: &cascade_zonedata::LoadedZoneBuilt) {
        let Some(upcoming) = &mut self.upcoming else {
            panic!("There is no upcoming instance of the zone");
        };

        assert!(
            upcoming.loaded.is_none() && upcoming.signed.is_none(),
            "The upcoming instance is not empty"
        );

        let reader = built.next().unwrap();
        let soa = reader.soa().clone();
        let num_records = {
            let n: usize = reader.regular_records().len();
            let n: u64 = n.try_into().unwrap();
            NonZeroU64::new(n).expect("the zone is non-empty")
        };

        upcoming.loaded = Some(LoadedInstance { soa, num_records });
    }
}

/// # Signing operations
impl Instances {
    /// Finish an ongoing (re-)sign.
    ///
    /// ## Panics
    ///
    /// Panics if:
    /// - There is no upcoming instance of the zone.
    /// - An upcoming signed instance already exists.
    pub fn finish_sign(&mut self, built: &cascade_zonedata::SignedZoneBuilt) {
        let Some(upcoming) = &mut self.upcoming else {
            panic!("There is no upcoming instance of the zone");
        };

        assert!(
            upcoming.signed.is_none(),
            "An upcoming signed instance already exists",
        );

        let reader = built.next_signed().unwrap();
        let soa = reader.soa().clone();
        let num_generated_records = {
            let n: usize = reader.generated_records().len();
            let n: u64 = n.try_into().unwrap();
            NonZeroU64::new(n).expect("the zone is non-empty")
        };
        let num_loaded_records = {
            // TODO: Make sure this is fast, maybe cache it during signing.
            let n: usize = reader.loaded_records().count();
            u64::try_from(n).unwrap()
        };

        upcoming.signed = Some(SignedInstance {
            soa,
            num_generated_records,
            num_loaded_records,
        });
    }
}

/// # Finalizing operations
impl Instances {
    /// Switch from the current instance to the upcoming one.
    ///
    /// The upcoming instance (which must exist) will replace the current one.
    ///
    /// ## Panics
    ///
    /// Panics if:
    /// - There is no upcoming instance.
    /// - The upcoming instance is malformed.
    /// - A re-sign took place but there is no current loaded instance.
    pub fn switch(&mut self) {
        // TODO: Save the current instance to a list of obsolete ones.

        let upcoming = self
            .upcoming
            .take()
            .unwrap_or_else(|| panic!("There is no upcoming instance"));
        let current = self.current.take();

        match upcoming {
            // A re-sign took place.
            UpcomingInstance {
                loaded: None,
                signed: Some(signed),
            } => {
                let CurrentInstance { loaded, signed: _ } = current.unwrap_or_else(|| {
                    panic!("A re-sign took place but there is no current loaded instance")
                });

                self.current = Some(CurrentInstance { loaded, signed });
            }

            // A new loaded instance has appeared.
            UpcomingInstance {
                loaded: Some(loaded),
                signed: Some(signed),
            } => {
                self.current = Some(CurrentInstance { loaded, signed });
            }

            // The upcoming instance is malformed.
            _ => {
                panic!("The upcoming instance is malformed")
            }
        }
    }

    /// Abandon the upcoming instance entirely.
    ///
    /// ## Panics
    ///
    /// Panics if an upcoming instance does not exist.
    pub fn abandon(&mut self) {
        // TODO: Add the upcoming instance to a list of abandoned ones.

        assert!(self.upcoming.is_some(), "Nothing to abandon");

        self.upcoming = None;
    }
}

/// # Persistence operations
impl Instances {
    /// Successfully restore the persisted instance.
    ///
    /// ## Panics
    ///
    /// Panics if there is no persisted instance. Panics if a current or
    /// upcoming instance already exists.
    pub fn restore(&mut self) {
        assert!(
            self.upcoming.is_none(),
            "Operations should not happen concurrently with restoration"
        );
        assert!(
            self.current.is_none(),
            "Restoration attempted after a new instance has been published"
        );

        let persisted = self
            .persisted
            .as_ref()
            .unwrap_or_else(|| panic!("There is no persisted instance"));

        self.current = Some(persisted.to_current());
    }
}

//----------- UpcomingInstance -------------------------------------------------

/// An upcoming instance of a zone.
///
/// This type holds information about an upcoming (loaded and signed) instance
/// of a zone, which is being generated by Cascade to replace the current one.
/// In case of a re-sign operation, only the signed instance is being replaced.
///
/// There are two reasons an upcoming instance may exist:
///
/// - A new instance of the zone is being loaded. The current instance can be
///   in any state. An upcoming loaded instance will exist, and an upcoming
///   signed instance might exist (if signing is enabled).
///
/// - The current instance of the zone is being re-signed. A current loaded
///   instance exists, but a current signed instance might not (e.g. if signing
///   was disabled and has now been enabled). An upcoming loaded instance will
///   not exist, but an upcoming signed instance will exist.
#[derive(Debug, Clone)]
pub struct UpcomingInstance {
    /// The upcoming loaded instance, if any.
    ///
    /// This describes the instance loaded from the zone source. It is [`Some`]
    /// if/when loading is complete; if a re-sign operation is happening, it is
    /// only [`None`].
    pub loaded: Option<LoadedInstance>,

    /// The upcoming signed instance, if any.
    ///
    /// This describes the signed instance generated by Cascade. It is [`Some`]
    /// if/when signing is complete.
    pub signed: Option<SignedInstance>,
    //
    // TODO:
    // - When the instance was initiated.
    // - The cause of initiation (e.g. reception of DNS NOTIFY).
    // - The policy used for generating the instance.
    //   (with such a field, policy changes during generation can be ignored.)
}

//----------- CurrentInstance --------------------------------------------------

/// The current/published instance of a zone.
///
/// This type holds information about the current (loaded and signed) instance
/// of a zone, which is published by Cascade.
#[derive(Debug, Clone)]
pub struct CurrentInstance {
    /// The current loaded instance.
    ///
    /// This describes the instance loaded from the zone source.
    pub loaded: LoadedInstance,

    /// The current signed instance.
    ///
    /// This describes the signed instance generated by Cascade.
    pub signed: SignedInstance,
    //
    // TODO:
    // - When the instance was published.
}

impl CurrentInstance {
    /// Build a [`PersistedInstance`] out of `self`.
    pub fn to_persisted(&self) -> PersistedInstance {
        let Self { loaded, signed } = self.clone();

        PersistedInstance { loaded, signed }
    }
}

//----------- PersistedInstance ------------------------------------------------

/// The instance of a zone that was current/published the last time Cascade was
/// running.
///
/// This type holds information about the [`CurrentInstance`] from the
/// _previous_ invocation of Cascade. On startup, Cascade will try to restore
/// that instance from disk; on success, this will become the current instance.
#[derive(Debug, Clone)]
pub struct PersistedInstance {
    /// The loaded instance.
    ///
    /// This describes the instance loaded from the zone source.
    pub loaded: LoadedInstance,

    /// The signed instance.
    ///
    /// This describes the signed instance generated by Cascade.
    pub signed: SignedInstance,
    //
    // TODO:
    // - When the instance was published.
}

impl PersistedInstance {
    /// Build a [`CurrentInstance`] out of `self`.
    pub fn to_current(&self) -> CurrentInstance {
        let Self { loaded, signed } = self.clone();

        CurrentInstance { loaded, signed }
    }
}

//----------- LoadedInstance ---------------------------------------------------

/// A loaded instance of a zone.
#[derive(Debug, Clone)]
pub struct LoadedInstance {
    /// The SOA record of this instance.
    ///
    /// The primary purpose of this field is to provide the SOA serial. We still
    /// store the full SOA because it is used sometimes, e.g. for sending IXFRs.
    pub soa: SoaRecord,

    /// The number of loaded records.
    ///
    /// This is the number of records in this instance. This includes any DNSSEC
    /// records (RRSIG, NSEC, etc.) in the instance, even if they will not be
    /// part of the signed instance. Notably, this also includes the SOA record.
    pub num_records: NonZeroU64,
    //
    // TODO:
    // - Instance ID.
    // - How the instance was loaded (time, source, duration, size).
    // - Whether the zone contains DNSSEC records (for pass-through mode).
    // - Basic details of the zone:
    //   - How many NS / DS / glue records are in the zone.
    //   - Total memory usage.
}

impl LoadedInstance {
    /// The SOA serial of this instance.
    pub fn serial(&self) -> Serial {
        self.soa.rdata.serial
    }
}

//----------- SignedInstance ---------------------------------------------------

/// A signed instance of a zone.
#[derive(Debug, Clone)]
pub struct SignedInstance {
    /// The SOA record of this instance.
    ///
    /// The primary purpose of this field is to provide the SOA serial. We still
    /// store the full SOA because it is used sometimes, e.g. for sending NOTIFY
    /// messages.
    pub soa: SoaRecord,

    /// The number of generated records.
    ///
    /// This is the number of records (RRSIG, NSEC, etc.) that were generated
    /// when building this instance. Notably, this includes the SOA record. The
    /// signed instance includes records from the loaded instance, but they are
    /// not counted here (for that see [`Self::num_loaded_records`]).
    pub num_generated_records: NonZeroU64,

    /// The number of records included from the loaded instance.
    ///
    /// This is the number of records from the associated loaded instance that
    /// are considered a part of the signed instance. This does not include
    /// DNSSEC records present in the loaded instance. Notably, this also
    /// excludes the loaded instance's SOA record.
    pub num_loaded_records: u64,
    //
    // TODO:
    // - Instance ID.
    // - How the instance was signed:
    //   - time, source, duration, size
    //   - Whether re-signing occurred, and what was re-signed.
    // - Basic details of the signed zone:
    //   - Total memory usage (excluding the loaded instance).
    // - DNSSEC details:
    //   - NSEC or NSEC3 records (incl. rollovers).
    //   - ZONEMD (incl. algorithms and rollovers).
    //   - Zone signing keys (incl. rollovers).
    //   - The earliest signature expiration time.
    //   - Extensions/overrides used during signing
    //     - See 'apex_{remove,extra}'.
}

impl SignedInstance {
    /// The SOA serial of this instance.
    pub fn serial(&self) -> Serial {
        self.soa.rdata.serial
    }
}
