name: Packaging

on:
  push:
    tags:
      - v*

  # Triggering on PRs and arbitrary branch pushes is not enabled because most of the time only the CI build should be
  # triggered, not the packaging build. In cases where you want to test changes to this workflow this trigger enables
  # you to manually invoke this workflow on an arbitrary branch as needed.
  workflow_dispatch:

jobs:
  package:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@fix-service-names-ending-in-d-in-rpms
    with:
      package_build_rules: pkg/rules/packages-to-build.yml
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      deb_extra_biuild_packages: libssl-dev
      #deb_apt_source: '"deb [arch=amd64 signed-by=/usr/share/keyrings/nlnetlabs-archive-keyring.gpg] https://packages.nlnetlabs.nl/linux/ubuntu '

      rpm_extra_build_packages: make openssl-devel
      rpm_scriptlets_path: pkg/rpm/scriptlets.toml
      rpm_yum_repo: |
        [nlnetlabs]
        name=NLnet Labs Testing
        baseurl=https://packages.nlnetlabs.nl/linux/centos/$releasever/main/$basearch
        enabled=1
